### ISSUE TITLE
The scrip update-all-workspaces.bat didn't work in workspaces_vs with more of 7 projects

### ISSUE THREAD

**Issue by jconcavi** [devonfw/devon-ide#113] opened 2019-05-20 15:00 UTC
Category: Bug

Severity:High

Expected behaviour: I expect that the script create a *.bat file for each workspace I have on my folder "workspace_vs"

Actual/current behaviour: Create the files with a maximum of 7, if have Space, finish abruptly

Steps to reproduce: Create 8 empty folders inside the folder "workspace_vs" and then hit update-all-workspaces.bat

Your environment - windows, 3.0.0 + win patch

**Comment by hohwille** [comment] 2019-06-03 09:07
There is no `workspace_vs` in devon-ide. This was introduced in an unofficial offline fork of `oasp4j-ide`. Further there is no `update-all-workspaces.bat` script in `devon-ide` at all:
https://github.com/devonfw/devon-ide/tree/master/scripts/src/main/resources

In order to create start scripts you need to provide the `create-script` argument. However, I assume you reported this issue in the wrong repository. As `oasp4j-ide` is more or less considered dead, you should try the new `devon-ide` and read the documentation to get started.

If you do not respond with further insights, I will close this issue as invalid.

**Comment by jconcavi** [comment] 2019-06-03 09:15
I understand that devon-ide was the repository used to the devon zip, to use in our environments. In the latest version delivered I have a folder called "_workspace_vs_",that folder is to contain the projects for the Visual Studio code.

If you take a look on the final result ([http://de-mucevolve02/files/devonfw/3.0.0/](http://de-mucevolve02/files/devonfw/3.0.0/)) you can see what i mean. 

If this is not the right repository to create the Incident, please tell me which is the good one. I understand that devon4j is not correct, too.

**Comment by maybeec** [comment] 2019-06-03 09:37
one question regarding this: why do we need workspaces_vs? it is really strange for me.
couldn't we simply have all workspaces in one workspaces folder? what is the issue here?

**Comment by sjimenez77** [comment] 2019-06-03 10:59
I do not think that this issue is **invalid**, since we need at least some clarification.

We need workspaces for Eclipse and for VS Code as both can store specific preferences for particular projects. For that reason we need the `workspace` and `workspace_vs` folders in case we use both IDEs, so the script should work as expected as @jconcavi has stated and @vapadwal confirmed some days ago.

On the other hand, if we do not want to take care of the `workspace_vs` folder and the devonfw VS Code projects we should mention it somewhere in the documentation, since this folder was included in the latest devonfw 2.4.0 and 3.0.0 releases and it is useful for Angular, Ionic, .NET and node.js projects (and in general for any project developed with this IDE). Any ideas?

**Comment by maybeec** [comment] 2019-06-03 11:36
@sjimenez77 can you provide an example which might be problematic here?
If the different IDEs provide different meta files, I don't care. the one are picked up by the one IDE, the other by the other. There should be no conflicts right?

As a second point: you can just create additional workspaces and use some just for eclipse, others for client part if you want to separate it like this. I am not separating these workspaces at all and don't have any issues.

I just want to prevent from introducing also workspaces_intellj or anything like this. Therefore, I am asking for the general problem, which should be solved by workspaces_vs, which I have not got yet.

**Comment by hohwille** [comment] 2019-06-03 13:28
I am fully with @maybeec and devon-ide already solves this without the need for an additional `workspace_ws` folder that is causing confusion and complexity.

> I do not think that this issue is invalid, since we need at least some clarification.

It is invalid according to what invalid is meant to be. The bug is about code that never existed in this repo. I do not want to kill the discussion with filing the issue as invalid. So keep commenting if you have furhter aspects to discuss here.
But `devon-ide` is a complete redesign and we can not fix bugs of an inofficial fork of `oasp4j-ide`. It at all this is your expectation then file the issue in https://github.com/oasp/oasp4j-ide/issues

**Comment by hohwille** [comment] 2019-06-03 15:07
> I understand that devon-ide was the repository used to the devon zip, to use in our environments.

If not already clarified. This understanding is wrong. The ZIP was created from  https://github.com/oasp/oasp4j-ide but the `workspaces_vs` folder also never existed there. These changes were made "in the dark" outside git and are untraceable to me.

**Comment by sjimenez77** [comment] 2019-06-03 15:55
@maybeec I know that here in the ADCenter some users are using different configurations in VS Code in different workspaces in the `workspace_vs` folder in order not to mess up things with the Eclipse `workspaces` folder. 

So, if we are capable of merging the workspaces for any IDE in only one `workspaces` folder for me it will be completely fine.

**Comment by maybeec** [comment] 2019-06-03 15:57
@sjimenez77  valid point. If you could ask some of these guys to post here, what problems they solve with this approach, we can maybe discuss how to do it with workspaces folder only or whether there is a real use case of workspaces_vs.
Otherwise, I would go for workspaces only for the moment.

**Comment by sjimenez77** [comment] 2019-06-04 06:22
@maybeec I know that here in the ADCenter some users are using different configurations in VS Code in different workspaces in the `workspace_vs` folder in order not to mess up things with the Eclipse `workspaces` folder. 

So, if we are capable of merging the workspaces for any IDE in only one `workspaces` folder for me it will be completely fine.

**Comment by hohwille** [comment] 2019-06-05 21:45
Please note that any user is still free to create any workspace folder inside `workspaces`. Besides the existance of the `main` workspace folder the `devon-ide` has no assumptions about this.
You can create `workspaces/vscode` and `worksapces/eclipse` if you think this is helpful.
This could be used as an alternative approach for the ADCenter in case they were facing any issues with mixed workspaces.

**Closed by hohwille** 2019-06-05 21:45 UTC
Labels: invalid
