### ISSUE TITLE
Errors during setup: Wrong paths

### ISSUE THREAD

**Issue by jambulud** [devonfw/devon-ide#145] opened 2019-07-22 10:50 UTC
Category: Bug

Severity: Medium

windows 10 x64, devon-ide 3.0.0-beta9, cmd and powershell

While installing devon-ide 3.0.0-beta9 i found some errors related with incorrect paths (eclipse, node and vscode)

Please, see the pdf attached.

[devon-ide.pdf](https://github.com/devonfw/devon-ide/files/3431272/devon-ide.pdf)

**Comment by hohwille** [comment] 2019-07-29 07:56
@jambulud thanks for testing and the feedback.
`Eclipse.app/Contents/Eclipse` seems to come from MacOs. It seems like some error related to #128 - I will check.

**Comment by hohwille** [comment] 2019-07-29 08:01
> To solve this, replace ${ECLIPSE_HOME}/eclipse/ to ${ECLIPSE_HOME}/eclipse/eclipse

The `ECLIPSE_HOME` variable needs to point to the eclipse directory that contains the `eclipse` binary. So it seems on (your) windows system for some reason `ECLIPSE_HOME` is pointing to the `software` directory (or to something entirely wrong such as `software/Eclipse.app/Content/Eclipse`). So the correct fix is to ensure that `ECLIPSE_HOME` is set correctly.

**Comment by hohwille** [comment] 2019-07-29 08:05
@jambulud #128 has been fixed immediately before `3.0.0-beta8`. Can you tell us which version of `devon-ide` you were using when facing this bug? If a version before `3.0.0-beta7` then most of your bug reporting is a duplicate that has already been fixed (except for the non absolute `eclipse` passing that I will fix asap).

**Comment by hohwille** [comment] 2019-07-29 08:09
Also note that `command -v «cmd»` is the same as `which «cmd»` and is checking that a programm (`«cmd»`) is on your path.
Passing the absolute path of the command does not make any sense. In that case we can simply delete the line or replace it with something like:
```
if [ ! -x "${ECLIPSE_HOME}/eclipse" ]
then
  doFail "Eclipse binary is not available in ${ECLIPSE_HOME}"
fi
```

**Comment by jambulud** [comment] 2019-07-29 08:19
> @jambulud #128 has been fixed immediately before `3.0.0-beta8`. Can you tell us which version of `devon-ide` you were using when facing this bug? If a version before `3.0.0-beta7` then most of your bug reporting is a duplicate that has already been fixed (except for the non absolute `eclipse` passing that I will fix asap).

I'm using  3.0.0-beta9

**Comment by hohwille** [comment] 2019-07-29 08:24
So it seems I figured out parts of the problem:
1. eclipse is not properly put on the path and therefore `command -v eclipse` fails. Needs to be fixed.
2. For some unclarified reason on your machine `ECLIPSE_HOME` was not pointing to the proper installation path of eclipse. This needs some investigation. Ideally you could add some `echo $ECLIPSE_HOME` debug output to your `eclipse` commandlet and let us know.

Everything else is just a consequence of these two issues. E.g.
https://github.com/devonfw/devon-ide/blob/10a34cd075c7518b2ae336537053caf58fe24f4c/scripts/src/main/resources/scripts/command/eclipse#L73
Is a fallback for MacOs. In the end it is properly detecting that your Eclipse is not properly installed at `$ECLIPSE_HOME` but simply because of 2.
The output log might be confusing and we could do some improvements as nice to have but this is not the actual bug.

**Comment by jambulud** [comment] 2019-07-29 08:24
> > To solve this, replace ${ECLIPSE_HOME}/eclipse/ to ${ECLIPSE_HOME}/eclipse/eclipse
> 
> The `ECLIPSE_HOME` variable needs to point to the eclipse directory that contains the `eclipse` binary. So it seems on (your) windows system for some reason `ECLIPSE_HOME` is pointing to the `software` directory (or to something entirely wrong such as `software/Eclipse.app/Content/Eclipse`). So the correct fix is to ensure that `ECLIPSE_HOME` is set correctly.

ECLIPSE_HOME is pointing to software/eclipse, but inside folder eclipse i have another "eclipse" folder, and inside this folder there is a eclipse.exe

The folders are structured as follows:
software
---- eclipse (ECLIPSE_HOME, folder 1)
-------- eclipse (folder 2)
------------ eclipse.exe (executable)
-------- .devon.software.version (file)

that's why i'm using ECLIPSE_HOME/eclipse (folder 2)/eclipse (executable)

**Comment by hohwille** [comment] 2019-07-29 08:37
Thanks for your feedback.
So the actual error with 2. is that the `doInstall` function was buggy and installed `eclipse` inside yet another `eclipse` folder on your machine. IMHO this is already fixed in #144 but we would need to verify this.

So the `ECLIPSE_HOME` variable is set properly. You found a bug in the actual installation process (technically `doExtract` function is extracting the downloaded archive file and then moves that to the software folder. There seems to be a bug in that procedure. We would need to retest this on windows with the latest SNAPSHOT build from `master` branch.)

**Comment by hohwille** [comment] 2019-07-29 08:42
So I fixed 1. with PR #148
We still need to investigate 2. and include a fix as necessary.

**Comment by hohwille** [comment] 2019-07-29 09:24
Maybe I should reimplement `doExtract`. The problem is that some tools provide download articats (archives such as  such that it detects if there is just a single folder that was extracted then it should use the contents of that folder while if there are multiple files and folders present

**Comment by hohwille** [comment] 2019-07-29 09:27
I have restest with the latest SNAPSHOT version in Windows10 Pro x64 VM and get the same error. So it seems the windows ZIP release contains `eclipse/*` while the macos DMG release contains the `Eclipse.app` directly not inside an `eclipse` folder. (see also my comment above).
So I will need to fix 2. and will update my PR #148 accordingly.

**Comment by hohwille** [comment] 2019-07-29 12:41
> https://update.code.visualstudio.com/latest/win32-x64-user/stable should be
https://update.code.visualstudio.com/latest/win32-x64-archive/stable

Wow! Excellent finding with perfect fix. Thanks. I will incorporate the change into PR #148 and think then all should be fine.

**Comment by hohwille** [comment] 2019-07-29 12:46
I can also confirm the node error. However it does not occur on my system (MacOS) but only in windows (in my VM):

> C:\projects\latest>devon node setup
Version v10.16.0 of node.js is already installed.
Running command: '/c/projects/latest/software/node/bin/node' -v
/c/projects/latest/scripts/command/../functions: line 52: /c/projects/latest/software/node/bin/node: No such file or directory
> 
> ******** ATTENTION ********
ERROR: Failed to verify installation of node.js ('/c/projects/latest/software/node/bin/node')
We are sorry for the inconvenience. Please check the above errors, resolve them and try again.
Exit code was 127
devon-ide environment variables have been set for C:\projects\latest

**Comment by hohwille** [comment] 2019-07-29 13:41
@jambulud thanks again for your intense testing and valuable feedback. I fixed all issues now.
As PR #145 has been merged, I can also close this issue.
I will try to release a new beta version soon.

**Closed by hohwille** 2019-07-29 13:41 UTC
Labels: blocker, bug, eclipse, scripts, windows
