### ISSUE TITLE
optimise devon alias addition to shell initialisation files

### ISSUE THREAD

**Issue by markusschuh** [devonfw/devon-ide#67] opened 2019-04-01 08:49 UTC
Category: Enhancement

Severity: Medium

Description of expected enhacement:

I see some potential (though rare) issues with the current code for addition of devon alias to bash (and other) initialisation scripts:
>   if [ ! -e ~/.bashrc ]
>   then
>     touch ~/.bashrc
>   fi
>   if ! grep -q "~/.devon/devon" ~/.bashrc
>   then
>     echo "Installing devon alias to your .bashrc"
>     echo "" >> ~/.bashrc
>     echo 'alias devon="source ~/.devon/devon"' >> ~/.bashrc
>   fi

E.g. if the user changes the entry - or devon-ide-scripts will ever introduce a change in the alias, this might several "alias" definitions - where later one overwrite earlier ones. Of course this can be fixed by the user - if it ever happens - without too much trouble. Nevertheless it would be good to execute the "exists" check more nearer to what was added. 
Unfortunately a script will never - except when sourced by interactive shell - see current alias definitions, so the "perfect" consistency check isn't possible anyway.

Another topic is that - from theory - alias definitions do not belong into $HOME/.bashrc - but since almost any existing bash implementations will try hard to also read this file for interactive bash start, it is indeed the typical convention for setup scripts to add the alias there. Otherwise the setup code would need to also check for alias definition in the other initialisation files - what makes the script code for that task quite lengthy.

I'll try to propose some optimisation and propose a pull request.

**Comment by hohwille** [comment] 2019-04-01 20:22
Sounds also like good suggestions and ideas.
Did I get you right that you also want to try if the alias is already defined in the current shell?

BTW: I put all this "installation logic" in an if block that checks if `~/.devon` has already been created. This will allow users to use `devon-ide` even without the alias by afterwards manually removing it because it will then not be recreated (of course an edge-case not expected to be used by mainstream users). Of course you are right that if I remove the `~/.devon` folder then the "installation logic" is executed once more. To avoid duplicating the alias, I grep for it. Surely, not perfect but should work in all the regular cases. Feel free to improve the mechanism...

**Comment by hohwille** [comment] 2019-04-02 16:39
@markusschuh you were completely right:
```
$ cat ~/.bashrc

alias devon="source ~/.devon/devon"

alias devon="source ~/.devon/devon"

alias devon="source ~/.devon/devon"
```

**Comment by hohwille** [comment] 2019-07-30 13:27
I assume that this problem occurred only in old releases of devon-ide. Since a long time I was unable to reproduce this issue anymore. I will close this.
If it ever occurres again, please reopen and provide additial information for analysis.

**Closed by hohwille** 2019-07-30 13:27 UTC
Labels: enhancement, linux, macOS, scripts
